spring:
  application:
    name: may-2024-spring

reference-data:
  engineTypes: Бензиновий, Дизельний, Гібридний
  fuels:
    - name: Дизельний
      types: Зимовий, Літній, Акртичний
    - name: Бензиновий
      types: A-95, A-98, A-100
    - name: Електрика
      types:
